apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-learning-app
  labels:
    app: argocd-learning-app
    version: v1.0.0
spec:
  replicas: 3
  selector:
    matchLabels:
      app: argocd-learning-app
  template:
    metadata:
      labels:
        app: argocd-learning-app
        version: v1.0.0
    spec:
      containers:
      - name: web-app
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: APP_NAME
          value: "ArgoCD Learning Hub"
        - name: APP_VERSION
          value: "1.0.0"
        volumeMounts:
        - name: website-content
          mountPath: /usr/share/nginx/html
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: website-content
        configMap:
          name: website-content
      - name: nginx-config
        configMap:
          name: nginx-config
